# Generated by Django 3.0.4 on 2020-04-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'churches'},
        ),
    ]
