# Generated by Django 3.0.4 on 2020-04-08 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='braintreePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('confirmation', models.CharField(max_length=42, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='btcPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('confirmation', models.CharField(max_length=42, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ccPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('confirmation', models.CharField(max_length=42, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('card_number', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=32)),
                ('zipcode', models.CharField(max_length=10)),
                ('auth_num', models.CharField(max_length=10)),
                ('tx_id', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='campaign.Campaign')),
            ],
        ),
    ]
