# Generated by Django 3.0.4 on 2020-04-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20200408_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btcpayment',
            name='donation',
        ),
        migrations.DeleteModel(
            name='braintreePayment',
        ),
        migrations.DeleteModel(
            name='btcPayment',
        ),
    ]
