# Generated by Django 3.0.4 on 2020-04-08 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryprofile',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministryprofile',
            name='reps',
            field=models.ManyToManyField(blank=True, related_name='represents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministryprofile',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='rep_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministryprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ministries', to='tag.Tag'),
        ),
    ]
