# Generated by Django 3.0.4 on 2020-04-19 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministry', '0003_auto_20200419_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administers_ministry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='reps',
            field=models.ManyToManyField(blank=True, related_name='represents_ministry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='rep_requests_ministry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ministry', to='tag.Tag'),
        ),
    ]
