# Generated by Django 3.0.4 on 2020-04-20 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ministry', '0004_auto_20200419_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='ministry.Ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
