version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lon_django
      - POSTGRES_PASSWORD=aoeuaoeuLONDJANGO
      - POSTGRES_DB=lon_django

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn frontend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django/lon/staticfiles
      - media_volume:/home/django/lon/mediafiles
      - uwsgi_socket:/home/django/uwsgi
    expose:
      - 8000
    env_file:
      - ./configs/django/env.prod.conf
    depends_on:
      - db

  nginx:
    build: ./configs/nginx
    volumes:
      - nginx_logs:/var/log
      - static_volume:/home/django/lon/staticfiles
      - media_volume:/home/django/lon/mediafiles
      - letsencrypt_certs:/etc/letsencrypt
      - uwsgi_socket:/tmp/uwsgi
    ports:
      - 80:80   # could be "8000:80" if necessary
      - 443:443
    depends_on:
      - django
    #command: sleep 999999
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


volumes:
  nginx_logs:
  postgres_data:
  static_volume:
  media_volume:
  letsencrypt_certs:
  uwsgi_socket:
