version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lon_django
      - POSTGRES_PASSWORD=aoeuaoeuLONDJANGO
      - POSTGRES_DB=lon_django

  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn frontend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - configs/django/env.conf
    depends_on:
      - db

  nginx:
    build: ./configs/nginx
    ports:
      - 80:80   # could be "8000:80" if necessary
    depends_on:
      - django

volumes:
  postgres_data:
