# Generated by Django 3.0.4 on 2020-04-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministry', '0001_initial'),
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='ministry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministry.MinistryProfile'),
        ),
    ]
